### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by vbmithr** [ocsigen/macaque#37]
It has been almost a year, and I need to pin this package in OPAM to actually have it working. Maybe it would be good to make a new release ?

**Comment by jpdeplaix** [comment]
I'll make a minor release later today.

**Comment by vbmithr** [comment]
On 21/07/2015 17:29, Jacques-Pascal Deplaix wrote:
> I'll make a minor release later today.

Cool, thanks!

**Comment by jpdeplaix** [comment]
Done. I've submitted a PR to opam-repository.
